server:
  port: 8090
mybatis:
  type-aliases-package: com.jk.model
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/1905?useUnicode=true&characterEncoding=utf-8
    username: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    solr:
      host: http://127.0.0.1:8080/solr
